#!/usr/bin/env ansible-playbook
---
- name: Create user
  remote_user: root
  hosts: all
  tasks:
    - { task: user, tag: user }

- name: Disable root SSH
  remote_user: "{{ ssh_user }}"
  hosts: all
  tasks:
    - { task: ssh, tag: ssh }