---
- name: Add docker engine apt key
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D
    state: present

- name: Add docker engine apt repository
  apt_repository:
    repo: https://apt.dockerproject.org/repo ubuntu-"{{ ansible_distribution_release }}" main
    filename: docker

- name: Remove legacy lxc-docker
  apt:
    name: lxc-docker
    state: absent

- name: Install docker engine
  apt:
    name: docker-engine
    state: latest

- name: Enable docker daemon auto start
  service:
    name: docker
    enabled: yes

- name: Start docker daemon
  service:
    name: docker
    state: start